# Generated by Django 3.2.9 on 2022-01-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='stars',
        ),
    ]
